In [10]:
pip install --user tensorflow


  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e4/14/d795bb156f8cc10eb1dcfe1332b7dbb8405b634688980aa9be8f885cc888/tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow-2.16.1-cp311-cp311-win_amd64.whl.metadata (3.5 kB)
  Obtaining dependency information for tensorflow-intel==2.16.1 from https://files.pythonhosted.org/packages/e0/36/6278e4e7e69a90c00e0f82944d8f2713dd85a69d1add455d9e50446837ab/tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata
  Using cached tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl.metadata (5.0 kB)
Using cached tensorflow-2.16.1-cp311-cp311-win_amd64.whl (2.1 kB)
Using cached tensorflow_intel-2.16.1-cp311-cp311-win_amd64.whl (377.0 MB)


ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device



In [2]:
import numpy as np
x=np.array(12)
x

array(12)

In [3]:
print(x.ndim)

0


In [4]:
x=np.array([1,2,3,4,5,6,7])
print(x)
x.ndim

[1 2 3 4 5 6 7]


1

In [5]:
x=np.array([[5,6,7,8,9],[2,3,4,5,6],[1,2,3,4,5]])
x

array([[5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5]])

In [6]:
x.ndim

2

In [7]:
x.shape

(3, 5)

In [8]:
x.dtype

dtype('int32')

In [9]:
from keras.datasets import mnist
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()
digit=train_images[4]
import matplotlib.pyplot as plt
plt.imshow(digit,cmap=plt.cm.binary)

ModuleNotFoundError: No module named 'tensorflow.python.tools'

In [ ]:
train_images.shape

In [ ]:
my_slice=train_images[10:100,:,:]
my_slice

In [ ]:
my_slice.shape

In [ ]:
myslice=train_images[:,14:,14:]
myslice.shape
digits=myslice[0]
plt.show(digit,cmap=plt.cm.binary)

In [ ]:
myslice=train_images[:,7:-7,7:-7]
myslice.shape
digits=myslice[0]
plt.show(digit,cmap=plt.cm.binary)

In [ ]:
n=(60000/128)
for i in range(int(60000/128)+1):
    data=train_images[128*i:128*(i+1)]
    print(data.shape)

In [11]:
import numpy as np
x=np.array([[1,3],[2,4]])
y=np.array([[2,4],[3,5]])

In [12]:
def naive_add(x,y):
    assert len(x.shape)==2
    assert x.shape==y.shape
    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j]+=y[i][j]
    return x
naive_add(x,y)

array([[3, 7],
       [5, 9]])

In [13]:
x=np.array([[1,3],[-1,4]])
def naive_relu(x):
    assert len(x.shape)==2
    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i][j]=max(x[i][j],0)
    return x
naive_relu(x)

array([[1, 3],
       [0, 4]])

In [14]:
x=np.array([[1,3],[-1,4]])
y=np.array([2,4])
print(x.shape)
print(y.shape)

(2, 2)
(2,)


In [15]:
def naive_add_matrixandvector(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    for i in range(x.shape[0]):
        for j in range(x.shape[0]):
            x[i][j]+=y[j]
    return x
print(naive_add_matrixandvector(x,y))

[[3 7]
 [1 8]]


In [16]:
x=np.array([1,3])
y=np.array([2,4])

In [17]:
def naive_vector_dot(x,y):
    assert len(x.shape)==1
    assert len(y.shape)==1
    assert x.shape[0]==y.shape[0]
    z=0
    for i in range(x.shape[0]):
        z+=x[i]*y[i]
    return z
print(naive_vector_dot(x,y))

14


In [23]:
x=np.array([[1,3],[-1,4]])
y=np.array([2,4])
def naive_matrix_tensor(x,y):
    assert len(x.shape)==2
    assert len(y.shape)==1
    assert x.shape[1]==y.shape[0]
    z=np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i]+=x[i][j]*y[j]
    return z
print(naive_matrix_tensor(x,y))

[14. 14.]


In [24]:
x=np.array([[0,1],[2,3],[4,5]])
print(x.shape)

(3, 2)


In [25]:
x.reshape((6,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
x.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
x=np.zeros((300,200))
x=np.transpose(x)
x.shape

(200, 300)